# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'jumpit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jumpit
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Firebase/Messaging', '~> 6.3.0'

  target 'jumpitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jumpit-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jumpit-tvOS

  target 'jumpit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
