const LOGIN_SUCCESS = 'SIGN_IN';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOG_OUT = 'LOG_OUT';
const SIGN_UP = 'SIGN_UP';
const ERROR_MSG = 'ERROR_MSG';
export { LOGIN_SUCCESS, LOG_OUT, SIGN_UP, ERROR_MSG, LOGIN_FAIL };
