const LOGIN_SUCCESS = 'SIGN_IN';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOG_OUT = 'LOG_OUT';
const SIGN_UP = 'SIGN_UP';
const ERROR_MSG = 'ERROR_MSG';
const GET_USER_INFO = 'GET_USER_INFO';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
const UPDATE_USER = 'UPDATE_USER';
const SEND_EMAIL = 'SEND_EMAIL';
const FORGET_PASSWORD = 'FORGET_PASSWORD';

const FETCH_START = 'FETCH_START';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_ERROR = 'FETCH_ERROR';
const ADD_DIET_SUCCESS = 'ADD_DIET_SUCCESS';
const DEL_DIET_SUCCESS = 'DEL_DIET_SUCCESS';
const CLEAR_PLAN = 'CLEAR_PLAN';
//workout

const STEP_COUNT = 'STEP_COUNT';
const DISTANCE = 'DISTANCE';
const FLIGHT_CLIME = 'FLIGHT_CLIME=';
// Foods
const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
const UPDATE_FOOD_VALUE = 'UPDATE_FOOD_VALUE';
const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
const FETCH_FOODS_ERROR = 'FETCH_FOODS_ERROR';

//measurement
const GET_HIGHBLOOD_DATA = 'GET_HIGHBLOOD_DATA';
const GET_SUGAR_DATA = 'GET_SUGAR_DATA';
const CLEAR_HIGHBLOOD = 'CLEAR_HIGHBLOOD';
const CLEAR_SUGAR = 'CLEAR_SUGAR';
const READ_STEPS = 'READ_STEPS';
const READ_FLOORS = 'READ_FLOORS';
const READ_DISTANCE = 'READ_DISTANCE';
const CLEAR_STEPS = 'CLEAR_STEPS';
const CLEAR_FLOORS = 'CLEAR_FLOORS';
const CLEAR_DISTANCE = 'CLEAR_DISTANCE';

export {
  LOGIN_SUCCESS,
  LOG_OUT,
  SIGN_UP,
  ERROR_MSG,
  LOGIN_FAIL,
  FETCH_ERROR,
  FETCH_SUCCESS,
  FETCH_START,
  ADD_DIET_SUCCESS,
  DEL_DIET_SUCCESS,
  GET_USER_INFO,
  CHANGE_PASSWORD,
  CHANGE_PASSWORD_FAIL,
  UPDATE_USER,
  ADD_FOOD_SUCCESS,
  UPDATE_FOOD_VALUE,
  UPDATE_FOOD_SUCCESS,
  DELETE_FOOD_SUCCESS,
  FETCH_FOODS_SUCCESS,
  FETCH_FOODS_ERROR,
  STEP_COUNT,
  DISTANCE,
  FLIGHT_CLIME,
  GET_HIGHBLOOD_DATA,
  GET_SUGAR_DATA,
  CLEAR_HIGHBLOOD,
  CLEAR_SUGAR,
  READ_STEPS,
  READ_FLOORS,
  READ_DISTANCE,
  CLEAR_STEPS,
  CLEAR_FLOORS,
  CLEAR_DISTANCE,
  SEND_EMAIL,
  FORGET_PASSWORD,
  CLEAR_PLAN
};
